test:js:
  image: node:latest
  cache:
    paths:
      - node_modules
      - .yarn-cache
  before_script:
    - npm install -g yarn
    - yarn install --pure-lockfile --cache-folder .yarn-cache
  script:
    - yarn test

test:python:
  image: python:latest
  before_script:
    - pip install flake8
    - pip install -r requirements.txt -U
    - touch templates/op.txt
  script:
    - flake8 .
    - python static.py
