test:js:
  image: node:latest
  cache:
    paths:
    - node_modules/
  before_script:
   - npm install --only=dev
  script:
   - npm test

test:python:
  image: python:latest
  before_script:
   - pip install pipenv
   - pipenv install --dev
   - touch templates/op.txt
  script:
   - flake8 .
   - pipenv run make-static
