sudo: false
dist: trusty
language: node_js
node_js:
    - "node"
python:
    - "3.6"
before_install:
    - python3 -V
    - pip3 -V
install:
    - npm install --only=dev
    - pip3 install flake8
script:
    - npm test
    - flake8 --ignore=E122,E126,E127,E128,E129 --max-line-length=140 .
