sudo: false
dist: trusty
language: node_js
node_js:
    - "node"
python:
    - "3.6"
before_install:
    - python3.6 -V
    - pip3.6 -V
install:
    - npm install --only=dev
    - pip3.6 install flake8
script:
    - npm test
    - flake8 .
