sudo: false
dist: trusty
language: node_js
node_js:
    - "node"
python:
    - "3.5"
before_install:
    - python3 -V
    - pip3 -V
install:
    - pip3 install -r requirements.txt
script:
    - flake8 --ignore=E122,E126,E127,E128,E129 --max-line-length=140 .
    - npm test
