language: python
addons:
  sonarcloud:
    organization: "sugrocks"
python:
  - "3.6"
install:
  - pip install flake8
  - pip install -r requirements.txt -U
  - touch templates/op.txt
script:
  - flake8 .
  - python static.py
  - sonar-scanner

